OPENA3XX_NETWORK_INTERFACE_CONFIGURATION_NAME = "opena3xx.network.interface"
OPENA3XX_SCAN_CIDR_RANGE_CONFIGURATION_NAME = "opena3xx.network.scan-range.cidr"
OPENA3XX_API_PORT_CONFIGURATION_NAME = "opena3xx.peripheral.api.port"
OPENA3XX_API_IP_ADDRESS_CONFIGURATION_NAME = "opena3xx.peripheral.api.ip"
OPENA3XX_API_SCHEME_CONFIGURATION_NAME = "opena3xx.peripheral.api.scheme"
